import React, { useEffect, useState } from 'react';
import type { RuntimeMode } from '../hooks/useRuntimeInfo.js';

type CredentialState = 'empty' | 'legacy' | 'locked' | 'unlocked';
interface ConfigStatus { hasKey: boolean; source: string; state: CredentialState }
interface GuideInfo { needsSetup: boolean; instructions: string[] }
interface ConfigPageProps { mode: RuntimeMode }
const validPassword = (v: string) => v.length >= 12 && v.length <= 128;

export function ConfigPage({ mode }: ConfigPageProps) {
  const [status, setStatus] = useState<ConfigStatus | null>(null);
  const [guide, setGuide] = useState<GuideInfo | null>(null);
  const [apiKey, setApiKey] = useState(''); const [masterPassword, setMasterPassword] = useState('');
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState<{ type: string; text: string } | null>(null);
  const [testing, setTesting] = useState(false); const [testResult, setTestResult] = useState<{ valid: boolean; error?: string } | null>(null);
  const refresh = async () => { const r = await fetch('/api/config/status'); if (r.ok) setStatus(await r.json() as ConfigStatus); };
  useEffect(() => { if (mode === 'public') { setLoading(false); return; } Promise.all([fetch('/api/config/status').then(r => r.json()), fetch('/api/config/guide').then(r => r.json())]).then(([s, g]) => { setStatus(s); setGuide(g); }).catch(() => setMessage({ type: 'error', text: '无法连接到服务器' })).finally(() => setLoading(false)); return () => { setApiKey(''); setMasterPassword(''); }; }, [mode]);
  if (mode === 'public') return <div style={{ maxWidth: 600, margin: '0 auto' }}><h2 className="section-title">本地配置</h2><div className="card" role="note">公共演示不会接收或保存 API Key，请在本机运行完整项目并设置 <code>HARNESS_MODE=local</code>。</div></div>;
  if (loading) return <div className="loading-text">正在加载配置…</div>;
  const state = status?.state ?? (status?.hasKey ? 'unlocked' : 'empty'); const needsMaster = state === 'empty' || state === 'legacy';
  const post = (path: string, body?: unknown) => fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const save = async () => { if (!apiKey.trim()) return setMessage({ type: 'error', text: '请输入 DeepSeek API Key' }); if (needsMaster && !validPassword(masterPassword)) return setMessage({ type: 'error', text: '主密码需要 12–128 个字符' }); try { const r = await post('/api/config/key', { key: apiKey.trim(), ...(needsMaster ? { masterPassword } : {}) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || '保存失败'); setApiKey(''); setMasterPassword(''); setMessage({ type: 'success', text: 'DeepSeek API Key 已安全保存' }); await refresh(); } catch (e) { setMessage({ type: 'error', text: e instanceof Error ? e.message : '保存失败' }); } };
  const unlock = async () => { const r = await post('/api/config/unlock', { masterPassword }); if (r.ok) { setMasterPassword(''); setMessage({ type: 'success', text: '凭据已解锁' }); await refresh(); } else setMessage({ type: 'error', text: '主密码错误' }); };
  const lock = async () => { await post('/api/config/lock'); setApiKey(''); setMasterPassword(''); setMessage({ type: 'info', text: '凭据已锁定' }); await refresh(); };
  const clear = async () => { const r = await fetch('/api/config/key', { method: 'DELETE' }); setMessage({ type: r.ok ? 'info' : 'error', text: r.ok ? 'DeepSeek 配置已删除' : '删除失败，请先解锁凭据' }); if (r.ok) await refresh(); };
  const test = async () => { setTesting(true); try { const r = await fetch('/api/agent/test-key', { method: 'POST' }); const d = await r.json(); setTestResult(d); setMessage({ type: d.valid ? 'success' : 'error', text: d.valid ? 'DeepSeek 连接测试成功' : `连接测试失败：${d.error ?? '未知错误'}` }); } catch { setMessage({ type: 'error', text: '无法测试 DeepSeek 连接' }); } finally { setTesting(false); } };
  return <div style={{ maxWidth: 600, margin: '0 auto' }}><h2 className="section-title">DeepSeek 配置</h2><div className="card"><strong>API Key 状态：</strong>{status?.hasKey ? '已配置' : '未配置'}（{state}）{status?.source === 'env' && <div>当前使用 DEEPSEEK_API_KEY 环境变量。</div>}</div>{guide?.needsSetup && <div className="card">请在 DeepSeek 控制台创建 API Key，然后在下方输入。部署环境建议使用 DEEPSEEK_API_KEY 环境变量。</div>}{state === 'locked' && <div className="card"><p>凭据已加密锁定，请输入主密码解锁。</p><label htmlFor="master-password">主密码</label><input id="master-password" className="input" type="password" value={masterPassword} onChange={e => setMasterPassword(e.target.value)} /><button className="btn btn-primary" onClick={() => void unlock()} disabled={!masterPassword}>解锁凭据</button></div>}{(state === 'empty' || state === 'legacy' || state === 'unlocked') && <div className="card"><label htmlFor="deepseek-api-key">DeepSeek API Key（不会回显）</label><input id="deepseek-api-key" className="input" type="password" value={apiKey} onChange={e => setApiKey(e.target.value)} />{needsMaster && <><p>主密码用于加密本地凭据，仅保存在你的记忆中；忘记后只能删除并重新配置。</p><label htmlFor="master-password">首次设置主密码（12–128 个字符）</label><input id="master-password" className="input" type="password" value={masterPassword} onChange={e => setMasterPassword(e.target.value)} /></>}<button className="btn btn-primary" onClick={() => void save()} disabled={!apiKey}>保存 DeepSeek Key</button>{state === 'unlocked' && <><button className="btn btn-secondary" onClick={() => void test()} disabled={testing}>测试连接</button><button className="btn btn-secondary" onClick={() => void lock()}>锁定凭据</button><button className="btn btn-danger" onClick={() => void clear()}>删除配置</button></>}</div>}{message && <div className="card" role="status">{message.text}</div>}{testResult && <div className="card">{testResult.valid ? '连接成功' : `连接失败：${testResult.error ?? ''}`}</div>}<div className="card">主密码仅用于解锁本地加密凭据，不会写入浏览器或日志。忘记主密码后无法恢复密钥，只能删除配置并重新设置。</div></div>;
}
